name: CI

on: [push]

jobs:
  php-security-check:
    name: PHP Security Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - with:
        php-version: '7.5'
        extensions: imagick
      - run: composer install
      - uses: StephaneBour/actions-php-security-checker@1.0
  build-test:
    name: PHPUnit Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - with:
        php-version: '7.5'
        extensions: imagick
      - run: composer install
      - run: composer test
